### ISSUE TITLE
When making pancakes it destroys the bucket

### ISSUE THREAD

**Issue by flynndenby** [CottonMC/EpicureanGastronomy#23] opened 2019-10-16 01:24 UTC
This should not destroy the bucket, unless they're some very metallic pancakes

**Comment by LemmaEOF** [comment] 2019-10-16 03:43
Duplicate of #13. I don't know what's causing recipe remainders to not work and I have idea how to fix it. I might just entirely rework the mod's interface stuff sometime to get it working.

**Closed as completed by LemmaEOF** 2019-10-16 03:43 UTC
Labels: bug
