### ISSUE TITLE
Server crash on bootup

### ISSUE THREAD

**Issue by ImAK9** [CottonMC/EpicureanGastronomy#7] opened 2019-04-26 21:10 UTC
Fabric Loader: 0.4.4 Build 138
Yarn: 1.14 Build 3
Epicurean Gastronomy: 2.1.2

Crashlog: https://pastebin.com/Jq7pcChs

**Comment by LemmaEOF** [comment] 2019-04-26 22:53
Duplicate of #6.

**Closed as completed by LemmaEOF** 2019-04-26 22:53 UTC
